Default: &defaults
  database: ig-testapp.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ig-testapp_test.sqlite3
  <<: *defaults

Staging:
  database: ig-testapp_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ig-testapp_production.sqlite3
  poolsize: 100
  <<: *defaults
